full_name=input("Enter your full name: ")
age=int(input("Enter your age: "))
student_id=input("Enter your student ID: ")
city=input("Enter your city: ")
university=input("Enter your university: ")
department=input("Enter your department: ")
email=input("Enter your email: ")
phone_number=int(input("Enter your phone number: "))
favorite_programming_language=input("Enter your favorite programming language: ")
programming_goal=input("Enter your programming goal: ")

print("=====================================")
print("        AKIBA STUDENT PROFILE       ")
print("=====================================\n")

print("\nName: ", full_name)
print("Student ID: ", student_id)
print("Age: ", age)
print("City: ", city)
print("University: ", university)
print("Department: ", department)
print("Email: ", email)
print("Phone: ", phone_number)
print("Favorite  Language: ", favorite_programming_language)
print("\nProgramming Goal: ","\n", programming_goal,"" "\n")

print("\n=====================================")